In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle

plt.style.use('default')

In [2]:
a = np.load(rf"E:\Aeronautics\fyp\DiffWake\data\horn\weather_data.npz", allow_pickle=True)
a

NpzFile 'E:\\Aeronautics\\fyp\\DiffWake\\data\\horn\\weather_data.npz' with keys: wind_speed, wind_direction, weight, windrose

In [3]:
ws = a['wind_speed']
wd = a['wind_direction']
w = a['weight']
wr = a['windrose']

In [9]:
a['wind_direction']

array([ 22.5,  67.5, 112.5, 157.5, 202.5, 247.5, 292.5, 337.5,  22.5,
        67.5, 112.5, 157.5, 202.5, 247.5, 292.5, 337.5,  22.5,  67.5,
       112.5, 157.5, 202.5, 247.5, 292.5, 337.5,  22.5,  67.5, 112.5,
       157.5, 202.5, 247.5, 292.5, 337.5,  22.5,  67.5, 112.5, 157.5,
       202.5, 247.5, 292.5, 337.5,  22.5,  67.5, 112.5, 157.5, 202.5,
       247.5, 292.5, 337.5,  22.5,  67.5, 112.5, 157.5, 202.5, 247.5,
       292.5, 337.5,  22.5,  67.5, 112.5, 157.5, 202.5, 247.5, 292.5,
       337.5,  22.5,  67.5])

In [18]:
wr

array({'wd': array([270.]), 'ws': array([13.5]), 'freq': array([0.06])},
      dtype=object)

In [22]:
# Create a simple weather case, single wd, ws and weight
wd_ = np.asarray([270.0])
ws_ = np.asarray([13.5])
w_ = np.asarray([1.0])
wr = np.array(dict(
    wd=wd_, ws=ws_, freq=w_
))

wd_, ws_, w_, wr

(array([270.]),
 array([13.5]),
 array([1.]),
 array({'wd': array([270.]), 'ws': array([13.5]), 'freq': array([1.])},
       dtype=object))

In [23]:
np.savez(rf"./data/simple/weather_data.npz",
         wind_speed=ws_,
         wind_direction=wd_,
         weight=w_,
         )

In [20]:
# reload
b = np.load(rf"./data/simple/weather_data.npz", allow_pickle=True)
b

NpzFile './data/simple/weather_data.npz' with keys: wind_speed, wind_direction, weight

In [21]:
b['wind_speed']

array([13.5])

In [24]:
c = np.load(rf"E:\Aeronautics\fyp\DiffWake\results\yaw_lbfgs\20260219_003433\arrays.npz", allow_pickle=True)
c

NpzFile 'E:\\Aeronautics\\fyp\\DiffWake\\results\\yaw_lbfgs\\20260219_003433\\arrays.npz' with keys: best_yaw, best_omega, per_case_power_MW, wind_dir_deg, wind_speed...

In [27]:
np.rad2deg(c['best_yaw'])

array([[25.        , 25.        , 12.52128107]])